n: 2
horizon: 200
expert_pth: "/home/hero/Documents/r2bc_sim_marl/r2bc_supervisors_final/buzz_wire/checkpoint_000100"
expert_policy_type: MAPPO
training:
  total_demonstrations: 96
  total_samples: 16
