# Base configuration for all experiments

#common parameters
seed: 42
frames_per_batch: 1000 #number of team frames collected per sampling iteration
n_iters: 250 #number of sampling and training iterations
# n_iters: 150
memory_size: 1000000 # replay buffer of each group can store this many frames
sparse_rewards: False #whether to use sparse rewards

#Training Hyperparameters
training:
  train_batch_size: 1024 #number of team frames sampled from replay buffer for each training iteration
  lr: 1e-4 #learning rate for optimizers
  max_grad_norm: 1.0 #max norm for gradients
  n_optimiser_steps: 500 #number of optimizer steps per training iteration
  # n_optimiser_steps: 250 #number of optimizer steps per training iteration
  checkpoint_interval: 10 #number of iterations between saving policy checkpoint
  # DDPG 
  gamma: 0.99 #discount factor
  polyak_tau: 0.001 #target network update rate
  num_critic_updates: 3


### Quick Test
# Base configuration for all experiments

# common parameters
# seed: 42
# frames_per_batch: 100 #number of team frames collected per sampling iteration
# n_iters: 20 #number of sampling and training iterations
# # n_iters: 150
# memory_size: 1000000 # replay buffer of each group can store this many frames
# horizon: 10
# sparse_rewards: True #whether to use sparse rewards

# #Training Hyperparameters
# training:
#   train_batch_size: 1024 #number of team frames sampled from replay buffer for each training iteration
#   lr: 1e-4 #learning rate for optimizers
#   max_grad_norm: 1.0 #max norm for gradients
#   n_optimiser_steps: 50 #number of optimizer steps per training iteration
#   # n_optimiser_steps: 250 #number of optimizer steps per training iteration
#   checkpoint_interval: 10 #number of iterations between saving policy checkpoint
#   # DDPG 
#   gamma: 0.99 #discount factor
#   polyak_tau: 0.001 #target network update rate
#   num_critic_updates: 3